jQuery(function($){var OSX={container:null,init:function(){$("a#iquiz").click(function(e){e.preventDefault();$("#osx-modal-quiz").modal({overlayId:'osx-overlay',containerId:'osx-container',closeHTML:null,minHeight:80,opacity:65,position:['2%',],overlayClose:true,onOpen:OSX.open,onClose:OSX.close})})},open:function(d){var self=this;self.container=d.container[0];d.overlay.fadeIn('slow',function(){$("#osx-modal-quiz",self.container).show();var title=$("#osx-modal-title",self.container);title.show();d.container.slideDown('slow',function(){setTimeout(function(){var h=$("#osx-modal-data",self.container).height()+title.height()+20;d.container.animate({height:h},200,function(){$("div.close",self.container).show();$("#osx-modal-data",self.container).show()})},300)})})},close:function(d){var self=this;d.container.animate({top:"-"+(d.container.height()+20)},500,function(){self.close()})}};OSX.init()});

jQuery(function($){var OSX={container:null,init:function(){$("a#ippt").click(function(e){e.preventDefault();$("#osx-modal-ppt").modal({overlayId:'osx-overlay',containerId:'osx-container',closeHTML:null,minHeight:80,opacity:65,position:['2%',],overlayClose:true,onOpen:OSX.open,onClose:OSX.close})})},open:function(d){var self=this;self.container=d.container[0];d.overlay.fadeIn('slow',function(){$("#osx-modal-ppt",self.container).show();var title=$("#osx-modal-title",self.container);title.show();d.container.slideDown('slow',function(){setTimeout(function(){var h=$("#osx-modal-data",self.container).height()+title.height()+20;d.container.animate({height:h},200,function(){$("div.close",self.container).show();$("#osx-modal-data",self.container).show()})},300)})})},close:function(d){var self=this;d.container.animate({top:"-"+(d.container.height()+20)},500,function(){self.close()})}};OSX.init()});

jQuery(function($){var OSX={container:null,init:function(){$("a#ibug").click(function(e){e.preventDefault();$("#osx-modal-debug").modal({overlayId:'osx-overlay',containerId:'osx-container',closeHTML:null,minHeight:80,opacity:65,position:['2%',],overlayClose:true,onOpen:OSX.open,onClose:OSX.close})})},open:function(d){var self=this;self.container=d.container[0];d.overlay.fadeIn('slow',function(){$("#osx-modal-debug",self.container).show();var title=$("#osx-modal-title",self.container);title.show();d.container.slideDown('slow',function(){setTimeout(function(){var h=$("#osx-modal-data",self.container).height()+title.height()+20;d.container.animate({height:h},200,function(){$("div.close",self.container).show();$("#osx-modal-data",self.container).show()})},300)})})},close:function(d){var self=this;d.container.animate({top:"-"+(d.container.height()+20)},500,function(){self.close()})}};OSX.init()});

jQuery(function($){var OSX={container:null,init:function(){$("a#ipixs").click(function(e){e.preventDefault();$("#osx-modal-poster").modal({overlayId:'osx-overlay',containerId:'osx-container',closeHTML:null,minHeight:80,opacity:65,position:['2%',],overlayClose:true,onOpen:OSX.open,onClose:OSX.close})})},open:function(d){var self=this;self.container=d.container[0];d.overlay.fadeIn('slow',function(){$("#osx-modal-poster",self.container).show();var title=$("#osx-modal-title",self.container);title.show();d.container.slideDown('slow',function(){setTimeout(function(){var h=$("#osx-modal-data",self.container).height()+title.height()+20;d.container.animate({height:h},200,function(){$("div.close",self.container).show();$("#osx-modal-data",self.container).show()})},300)})})},close:function(d){var self=this;d.container.animate({top:"-"+(d.container.height()+20)},500,function(){self.close()})}};OSX.init()});

jQuery(function($){var OSX={container:null,init:function(){$("a#iadzap").click(function(e){e.preventDefault();$("#osx-modal-adzap").modal({overlayId:'osx-overlay',containerId:'osx-container',closeHTML:null,minHeight:80,opacity:65,position:['2%',],overlayClose:true,onOpen:OSX.open,onClose:OSX.close})})},open:function(d){var self=this;self.container=d.container[0];d.overlay.fadeIn('slow',function(){$("#osx-modal-adzap",self.container).show();var title=$("#osx-modal-title",self.container);title.show();d.container.slideDown('slow',function(){setTimeout(function(){var h=$("#osx-modal-data",self.container).height()+title.height()+20;d.container.animate({height:h},200,function(){$("div.close",self.container).show();$("#osx-modal-data",self.container).show()})},300)})})},close:function(d){var self=this;d.container.animate({top:"-"+(d.container.height()+20)},500,function(){self.close()})}};OSX.init()});

jQuery(function($){var OSX={container:null,init:function(){$("a#igame").click(function(e){e.preventDefault();$("#osx-modal-game").modal({overlayId:'osx-overlay',containerId:'osx-container',closeHTML:null,minHeight:80,opacity:65,position:['2%',],overlayClose:true,onOpen:OSX.open,onClose:OSX.close})})},open:function(d){var self=this;self.container=d.container[0];d.overlay.fadeIn('slow',function(){$("#osx-modal-game",self.container).show();var title=$("#osx-modal-title",self.container);title.show();d.container.slideDown('slow',function(){setTimeout(function(){var h=$("#osx-modal-data",self.container).height()+title.height()+20;d.container.animate({height:h},200,function(){$("div.close",self.container).show();$("#osx-modal-data",self.container).show()})},300)})})},close:function(d){var self=this;d.container.animate({top:"-"+(d.container.height()+20)},500,function(){self.close()})}};OSX.init()});

jQuery(function($){var OSX={container:null,init:function(){$("a#iminute").click(function(e){e.preventDefault();$("#osx-modal-minute").modal({overlayId:'osx-overlay',containerId:'osx-container',closeHTML:null,minHeight:80,opacity:65,position:['2%',],overlayClose:true,onOpen:OSX.open,onClose:OSX.close})})},open:function(d){var self=this;self.container=d.container[0];d.overlay.fadeIn('slow',function(){$("#osx-modal-minute",self.container).show();var title=$("#osx-modal-title",self.container);title.show();d.container.slideDown('slow',function(){setTimeout(function(){var h=$("#osx-modal-data",self.container).height()+title.height()+20;d.container.animate({height:h},200,function(){$("div.close",self.container).show();$("#osx-modal-data",self.container).show()})},300)})})},close:function(d){var self=this;d.container.animate({top:"-"+(d.container.height()+20)},500,function(){self.close()})}};OSX.init()});

jQuery(function($){var OSX={container:null,init:function(){$("a#iblock").click(function(e){e.preventDefault();$("#osx-modal-block").modal({overlayId:'osx-overlay',containerId:'osx-container',closeHTML:null,minHeight:80,opacity:65,position:['2%',],overlayClose:true,onOpen:OSX.open,onClose:OSX.close})})},open:function(d){var self=this;self.container=d.container[0];d.overlay.fadeIn('slow',function(){$("#osx-modal-block",self.container).show();var title=$("#osx-modal-title",self.container);title.show();d.container.slideDown('slow',function(){setTimeout(function(){var h=$("#osx-modal-data",self.container).height()+title.height()+20;d.container.animate({height:h},200,function(){$("div.close",self.container).show();$("#osx-modal-data",self.container).show()})},300)})})},close:function(d){var self=this;d.container.animate({top:"-"+(d.container.height()+20)},500,function(){self.close()})}};OSX.init()});